# crypto-config.yaml — 1 Org (LandReg), 3 peers, admin + many customers
OrdererOrgs:
  - Name: Orderer
    Domain: landreg.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: LandReg
    Domain: landreg.com
    EnableNodeOUs: true
    Template: { Count: 3 }
    Users:
      Count: 10
